import 'package:flutter/material.dart';
import 'package:get/get.dart';

class TranslationService extends Translations {
  static Locale? get locale => Get.deviceLocale; // Get the device locale

  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "skip": "skip",
          "privacy_policy": "Privacy Policy",
          "privacy_policy_state":
              "We follow a policy of keeping the data safe and ensuring that the data is preserved and preserved",
          "multiple_payment_methods": "Multiple Payment Methods",
          "multiple_payment_methods_state":
              "Pay for the products you purchase on delivery or with a bank card",
          "data_order": "Data Order",
          "data_order_state":
              "Arranging the data in an accurate and orderly manner that makes it easy for the user to review and modify it.",
          "next": "Next",
          "welcome": "Welcome to Waiter Bail Cashier",
          "create": "Create Account",
          "login": "Login",
          "email": "Email",
          "email_hint": "email@gmail.com",
          "pass": 'Password',
          "pass_hint": "*********",
          "problem": "Problem logging in?",
          "phone": "Phone Number",
          "phone_hint": "595959595",
          "name": "Name",
          "name_hint": "Enter Name",
          "address": "Address",
          "address_hint": "Enter address",
          "home": "Home",
          "item": "Items",
          "receipts": "Receipts",
          "more": "More",
          "search": 'Search from here',
          "addtocart": 'Add to Cart',
          "itemsmustbeadded": "Items must be Added",
          "confirmyourorder": "Confirm Your Order",
          "cancelyourorder": 'Are you sure to cancel the request?',
          "cancel": "Cancel",
          "confirmodrder": "Confirm Order",
          "added": 'Item added to Cart',
          "addederror": 'Error adding item to cart',
          "itemicrees": "Item count has been increased",
          "additem": 'Add Item',
          "addcate": 'Add Category',
          "edit": "Edit",
          "delete": "Delete",
          "deletecate": 'Category deleted successfully',
          "deletecateerror": 'Error deleting Category',
          'checkdata': 'Enter the required data',
          "editcate": 'Category editing successfully',
          "editcateerror": "Error Editing Category",
          "edititem": 'Item editing successfully',
          "edititemerror": "Error Editing Category",
          "deleteitem": 'The item was deleted successfully',
          "deleteitemerror": 'Error deleting item',
          "itemaddsuccess": 'Item added successfully',
          "itemaddfaild": "Error adding item",
          "profile": "Profile Personly",
          "accountinfo": "Account Information",
          "change_pass": 'Change Password',
          "logout": "Logout",
          "debt": "Debt",
          "rest": "Rest",
          "all": "All",
          "noreceiptdebt": "No credit Receipts",
          "noreceiptrest": "There are no remaining Receipts",
          "noreceipt": "No Receipts",
          "customers": "Customers",
          "shift": "Shift",
          "back_office": "Back Office",
          "contact_us": "Contact Us",
          "Application_information": "App info",
          "share_app": "Share App",
          "language": "Language",
          "terms_use": "Terms of Use",
          "follow_us": "Follow Us",
          "add_customer": "Add Customer",
          "Wallet_Balance": "Wallet Balance",
          "debt_money": 'Debt Money',
          "no_recipet": "There are no invoices to display",
          "Purchases": 'Purchases',
          'account_date': "Account Creation Date",
          'editdata': "Edit Information",
          "delete_customer": "Delete Customer",
          "delete_customer_confirm": "Are you sure to delete the client",
          "searchbyreceiptnumber": 'Search from here by the receipt number',
          "refund": "Refund",
          "print": "Print",
          "Total": "Total",
          "Discount": "Discount",
          "total_summation": 'total summation ',
          'amount_paid': "Amount Paid",
          "Rest": "Rest",
          "employee": "Employee",
          "cofirmrefund": 'Confirm refund',
          "confirmrefundmessage": "Are you sure to refund the request",
          "bar_code": "Bar Code",
          "scan": 'Scan the barcode on the item',
          "itemnotfound": "The Item is not added",
          "clickbuttonadd": "Click on the add -on button to add a new item",
          "productnamehint": "Grapes",
          "productcatrgoryhint": 'Without category',
          "Selling": "Selling B",
          "Unity": "Unit",
          "Weight": "Weight",
          "selling_price": "Selling Price",
          "hint_selling_price": "15",
          "Cost": "Cost",
          "hint_Cost": "10",
          "product_location": "The location of the Item in the Warehouse",
          "Optional": '(Optional)',
          "Enter_the_item_site_in_the_warehouse":
              "Enter the item site in the warehouse",
          "sku": "sku",
          "hint_barcode": "1010100001110101010",
          "Opening_the_lens": "Opening the lens",
          "Trace_inventory": "Trace Inventory",
          "compulsory": '(compulsory)',
          "The_quantity_available_1234": 'The quantity available 1234 ',
          "item_status": 'Item Status',
          "color": 'Color',
          "image": "Image",
          "import": "Import",
          'taking_picture': 'Taking Picture',
          'Data_Confirm': "Data Confirm",
          "areyousuretoaddproduct": 'Are you sure to add the Item?',
          "hint_category_name": "Enter a category name",
          "category_status": "category status",
          "create_item": "Create Item",
          "cate": "Category",
          "areyousuretoaddcategory": 'Are you sure to add Category',
          'Category_added_successfully': "Category added successfull",
          "done": "Done",
          "cart": 'shopping basket',
          "no_customers": "There's no customers",
          "note": "Note",
          'writeanote': 'write a note',
          "confirm": "Confirm",
          "numberover": "The phone number must not exceed 10 digits.",
          "numberless": "The phone number must not be less than 10 digits.",
          "Customer_added_successfully": "Customer added successfully",
          "Add_client_failed": "Error adding Customer",
          "no_items": 'There are no items',
          "add_discount": "Add Discount",
          'pay_the_bill': "Pay the bill",
          'Natural_push': "Natural push",
          "Add_the_rest_to_the_wallet": "Add the rest to the wallet",
          'credit_invoice': "credit invoice",
          'paying off': 'Paying Off',
          'cash payment': 'cash payment',
          'Payment by Visa': 'Payment by Visa',
          "Pay by wallet": "Pay by wallet",
          "You must enter the invoice status":
              "You must enter the invoice status",
          "You must enter payment status": "You must enter payment status",
          "You must enter the amount paid": "You must enter the amount paid",
          'send link': 'send Receipt',
          'WhatsApp': 'WhatsApp',
          'Gmail': 'Gmail',
          'Print link': 'Print Receipt',
          'Are you sure to send the request':
              'Are you sure to send the request',
          "change_password": "Change Password",
          'Current Password': "Current Password",
          'New Password': "New Password",
          'confirm password': "Confirm Password",
          'Password modified successfully': "Password modified successfully",
          'Error modifying password': "Error modifying password",
          "logout_state": "Are you sure you are logged out of the account?",
          'Add the remainder to the wallet with an amount':
              'Add the remainder to the wallet with an amount',
          'the rest': 'The rest',
          'credit invoice for the amount': 'Credit invoice for the amount',
          "sug": 'complaints and suggestions',
          "message": "Message",
          "submit": "Submit",
          "About us": 'About us',
          "who are we?": 'Who Are We?',
          'Why us?': 'Why us?',
          'terms of use': 'terms of use',
          "sent_sug":
              "Your complaint or suggestion has been sent,\nand we will respond to you as soon as possible.",
          "shift_begin": "Enter the starting cash",
          "begin_shift": "Start Shift",
          "shift management": "Shift Management",
          "shift lock": "Shift Lock",
          "shift number": "Shift Number",
          "open shift": "Open Shift",
          "cash drawer": "Cash Drawer",
          "cash in the beginning": "Cash in the Beginning",
          "cash payments": "Cash Payments",
          "cash refunds": "Cash Refunds",
          "Amounts paid": "Amounts Paid",
          "amounts withdrawn": "Amounts Withdrawn",
          "expected cash amount": "Expected Cash Amount",
          "Sales Summary": "Sales Summary",
          "Total sales": "Total Sales",
          "Refunds": "Refunds",
          "Discounts": "Discounts",
          "Net sales": "Net sales",
          "Cash": "Cash",
          "Card": "Card",
          "comment": "Comment",
          "Payments/Withdrawals": "Payments\\Withdrawals",
          "tickets": "Open Tickets",
          "save": "Save",
          "Pay": "Pay",
          "Save the ticket": "Save the ticket",
          "ticket": "Ticket",
          "Ticket saved": "Ticket saved",
          "Error saving ticket": "Error saving ticket",
          "Ticket terminated": "Ticket Ending",
          "Error ending ticket": "Error Ending Ticket",
          "Ticket modified successfully": "Ticket modified successfully",
          "Error modifying the ticket": "Error modifying the ticket",
          "The ticket has been successfully deleted.":
              "The ticket has been successfully deleted.",
          "Error deleting ticket": "Error deleting ticket"
        },
        'ar': {
          "Ticket saved": "تم حفظ التذكرة بنجاح",
          "Error saving ticket": "خطأ في حفظ التذكرة",
          "Ticket terminated": "تم إنهاء التذكرة بنجاح",
          "Error ending ticket": "خطأ في إنهاء التذكرة",
          "Ticket modified successfully": "تم تعديل التذكرة بنجاح",
          "Error modifying the ticket": "خطأ في تعديل التذكرة",
          "The ticket has been successfully deleted.": "تم حذف التذكرة بنجاح.",
          "Error deleting ticket": "خطأ في حذف التذكرة",
          "ticket": "تذكرة",
          "Save the ticket": "حفظ التذكرة",
          "Pay": "السداد",
          "save": "حفظ",
          "tickets": "التذاكر المفتوحة",
          "Payments/Withdrawals": "المبالغ المدفوعة \\ المسحوبة",
          "comment": "تعليق",
          "begin_shift": "ابدأ المناوبة",
          "shift management": "إدارة المناوبة",
          "shift lock": "إقفال المناوبة",
          "shift number": "رقم المناوبة",
          "open shift": "فتح المناوبة",
          "cash drawer": "درج النقدية",
          "cash in the beginning": "النقدية في البداية",
          "cash payments": "المدفوعات النقدية",
          "cash refunds": "المبالغ المستردة نقدا",
          "Amounts paid": "المبالغ المدفوعة",
          "amounts withdrawn": "المبالغ المسحوبة",
          "expected cash amount": "المبلغ النقدي المتوقع",
          "Sales Summary": "ملخص المبيعات",
          "Total sales": "إجمالي المبيعات",
          "Refunds": "المبالغ المستردة",
          "Discounts": "الخصومات",
          "Net sales": "صافي المبيعات",
          "Cash": "نقدا",
          "Card": "بطاقة",
          "shift_begin": 'قم بإدخال نقدية البداية',
          "sent_sug":
              'تم ارسال شكواكم او اقتراحكم,\n وسيتم الرد عليكم باقرب وقت',
          'terms of use': 'شروط الاستخدام',
          'Why us?': 'لماذا نحن؟',
          "who are we?": 'من نحن؟',
          "About us": 'نبذة عنا',
          "submit": "ارسال",
          "message": "الرسالة",
          "sug": 'الشكاوي والاقتراحات',
          'Add the remainder to the wallet with an amount':
              'إضافة باقي للمحفظة بمبلغ',
          'the rest': 'الباقي',
          'credit invoice for the amount': 'فاتورة دائنة بمبلغ',
          "logout_state": 'هل أنت متأكد من تسجيل خروجك من الحساب',
          'Password modified successfully': 'تم تعديل كلمة المرور بنجاح',
          'Error modifying password': 'خطأ في تعديل كلمة المرور',
          "change_password": "تغيير كلمة المرور",
          'Current Password': 'كلمة المرور الحالية',
          'New Password': 'كلمة المرور الجديدة',
          'confirm password': 'تأكيد كلمة المرور',
          "skip": "تخطي",
          "privacy_policy": "سياسة الخصوصية",
          "privacy_policy_state":
              "نحن نتبع سياسة الحفاظ على البيانات آمنة والتأكد من الحفاظ على البيانات وصونها",
          "multiple_payment_methods": "طرق دفع متعددة",
          "multiple_payment_methods_state":
              "ادفع مقابل المنتجات التي تشتريها عند استلامها أو ببطاقة مصرفية",
          "data_order": "ترتيب البيانات",
          "data_order_state":
              "ترتيب البيانات بشكل دقيق ومنظم يسهل على المستخدم مراجعتها وتعديلها",
          "next": "التالي",
          "welcome": "مرحبا بكم في ويتر بيل كاشير",
          "create": "إنشاء حساب",
          "login": 'تسجيل دخول',
          "email": "البريد الالكتروني",
          "email_hint": "email@gmail.com",
          "pass": 'كلمة المرور',
          "pass_hint": "*********",
          "problem": "مشكلة في تسجيل الدخول؟",
          "phone": "رقم الهاتف",
          "phone_hint": "5959595959",
          "name": "الاسم",
          "name_hint": " أدخل الاسم",
          "address": "العنوان",
          "address_hint": "أدخل العنوان",
          "home": "الرئيسية",
          "item": "العناصر",
          "receipts": "الإيصالات",
          "more": "المزيد",
          "search": 'ابحث من هنا',
          "addtocart": 'أضف إلى السلة',
          "itemsmustbeadded": "يجب اضافة عناصر",
          "confirmyourorder": "أكد طلبك",
          "cancelyourorder": 'هل أنت متأكد من إالغاء الطلب',
          "cancel": "إلغاء",
          "confirmodrder": "تأكيد الطلب",
          "added": 'تم اضافة العنصر الى السلة',
          "addederror": 'خطأ في اضافة العنصر الى السلة',
          "itemicrees": "تم زيادة عدد العنصر",
          "additem": 'إضافة عنصر',
          "addcate": 'إضافة فئة',
          "edit": "تعديل",
          "delete": "حذف",
          "deletecate": 'تم حذف الفئة بنجاح',
          "deletecateerror": 'خطأ في حذف العنصر',
          'checkdata': 'أدخل البيانات المطلوبة',
          "editcate": 'تم تعديل الفئة بنجاح',
          "editcateerror": "خطأ في تعديل الفئة",
          "edititem": 'تم تعديل العنصر بنجاح',
          "edititemerror": "خطأ في تعديل العنصر",
          "deleteitem": 'تم حذف العنصر بنجاح',
          "deleteitemerror": 'خطأ في حذف العنصر',
          "itemaddsuccess": 'تم إضافة العنصر بنجاح',
          "itemaddfaild": "خطأ في اضافة العنصر",
          "profile": 'الملف الشخصي',
          "accountinfo": 'معلومات الحساب',
          "change_pass": 'تغيير كلمة السر',
          "logout": "تسجيل خروج",
          "debt": "دين",
          "rest": "باقي",
          "all": "الكل",
          "noreceiptdebt": "لا يوجد فواتير دائنة",
          "noreceiptrest": "لا يوجد فواتير متبقية الرصيد",
          "noreceipt": "لا يوجد فواتير",
          "customers": "العملاء",
          "shift": "المناوبة",
          "back_office": 'المكتب الخلفي',
          "contact_us": 'تواصل معنا',
          "Application_information": "معلومات التطبيق",
          "share_app": 'مشاركة التطبيق',
          "language": "اللغة",
          "terms_use": 'شروط الاستخدام',
          "follow_us": "تابعنا",
          "add_customer": 'إضافة عميل',
          "Wallet_Balance": 'رصيد المحفظة',
          "debt_money": 'مدين بمبلغ',
          "no_recipet": "لا يوجد فواتير لعرضها",
          "Purchases": 'المشتريات',
          'account_date': 'تاريخ إنشاء الحساب',
          'editdata': 'تعديل البيانات',
          'delete_customer': 'حذف العميل',
          "delete_customer_confirm": 'هل أنت متأكد من حذف العميل',
          "searchbyreceiptnumber": "ابحث من هنا بواسطة رقم الايصال",
          "refund": "استرداد",
          "print": "طباعة",
          "Total": "المجموع",
          "Discount": "الخصم",
          "total_summation": 'المجموع الكلي ',
          'amount_paid': 'المبلغ المدفوع',
          "Rest": "الباقي",
          "employee": "الموظف",
          "cofirmrefund": 'تأكيد الاسترداد',
          "confirmrefundmessage": 'هل أنت متأكد من استرداد الطلب',
          "bar_code": 'بار كود',
          "scan": 'امسح البار كود على العنصر',
          "itemnotfound": "العنصر غير مضاف ",
          "clickbuttonadd": "اضغط على زر إضافة العنصر لإضافة عنصر جديد",
          "productnamehint": "عنب",
          "productcatrgoryhint": 'بدون فئة',
          "Selling": "يتم البيع ب",
          "Unity": "بالوحدة",
          "Weight": "بالوزن",
          "selling_price": 'سعر البيع',
          "hint_selling_price": "15",
          "Cost": "التكلفة",
          "hint_Cost": "10",
          "product_location": "موقع العنصر في المستودع",
          "Optional": '(اختياري)',
          "Enter_the_item_site_in_the_warehouse":
              "أدخل موقع العنصر في المستودع",
          "sku": "01011",
          "hint_barcode": "1010100001110101010",
          "Opening_the_lens": "فتح العدسة",
          "Trace_inventory": "تعقب المخزون",
          "compulsory": '(اجباري)',
          "The_quantity_available_1234": 'الكمية المتوفرة 1234',
          "item_status": 'حالة العنصر',
          "color": 'اللون',
          "image": " صورة",
          "import": " استيراد",
          'taking_picture': 'التقاط صورة',
          'Data_Confirm': "تأكيد البيانات",
          "areyousuretoaddproduct": 'هل أنت متأكد من إضافة العنصر',
          "areyousuretoaddcategory": 'هل أنت متأكد من إضافة الفئة',
          "hint_category_name": "أدخل اسم الفئة",
          "category_status": 'حالة الفئة',
          "create_item": 'إنشاء عنصر',
          "cate": "الفئة",
          'Category_added_successfully': 'تم إضافة الفئة بنجاح',
          "Error_adding_category": "خطأ في اضافة الفئة",
          "done": "تم",
          "cart": "سلة المشتريات",
          "no_customers": "لا يوجد زبائن",
          "note": "ملاحظة",
          "writeanote": 'أكتب أي ملاحظة',
          "confirm": "تأكيد",
          "numberover": "يجب الا يزيد رقم الهاتف عن 10 ارقام",
          "numberless": "يجب الا يقل رقم الهاتف عن 10 ارقام",
          "Customer_added_successfully": "تم إضافة العميل بنجاح",
          "Add_client_failed": "خطأ في إضافة العميل",
          "no_items": 'لا يوجد عناصر',
          'add_discount': 'إضافة خصم',
          'pay_the_bill': 'دفع الفاتورة',
          'Natural_push': 'دفع طبيعي',
          "Add_the_rest_to_the_wallet": 'إضافة الباقي للمحفظة',
          'credit_invoice': 'فاتورة دائنة',
          'paying off': 'الدفع',
          'cash payment': 'الدفع كاش',
          'Payment by Visa': 'الدفع عن طريق الفيزا',
          "Pay by wallet": "الدفع عن طريق المحفظة",
          "You must enter the invoice status": "يجب إدخال حالة الفاتورة",
          "You must enter payment status": "يجب إدخال حالة الدفع",
          "You must enter the amount paid": "يجب إدخال المبلغ المدفوع",
          'send link': 'إرسال الوصل',
          'WhatsApp': 'واتس اب',
          'Gmail': 'الجيميل',
          'Print link': 'طباعة الوصل',
          'Are you sure to send the request': 'هل أنت متأكد من إرسال الطلب'
        },
      };
}
